targets:
  $default:
    sources:
      - lib/**
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          separate_models: true
          build_only_models: true
          ignore_headers: true
          input_folder: swagger/
          output_folder: lib/
          use_default_null_for_lists: false
