name: ynab_api
version: 0.1.1
description: Unofficial API for interacting with https://api.ynab.com/
repository: https://github.com/Luckey-Elijah/ynab_api

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  http: ^1.1.0
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.11.10
  very_good_analysis: ^5.0.0+1
